# Generated by Django 4.2.2 on 2023-07-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WRapi', '0002_location_period_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
